### ISSUE TITLE
EE trial project

### ISSUE THREAD

**Issue by QuanLe8191** [SJSURoboticsTeam/urc-central-2021#105]
## Introduction
Candidates for the SJSU Robotics EE division should have a strong focus on schematic capture, and PCB layouts as well as the ability to extract information from a datasheet. This is used to test the student’s understanding of basic electrical components that we will be using for the rover throughout the course of the year. In addition to the EE skills required, you will be required to have basic knowledge of interfacing the electrical components with a microprocessor. 

This trial project will be evaluated by completion and by adherence to project rules/guidelines. 

### Goal
In this trial project, you will be building a module that will allow a microcontroller to drive a brushed DC motor at 24V and can supply up to 3A.

DRV8801 is a commonly used motor driver in SJSU Robotics. 

On the date of the trial project review, you will have to present your schematic, layout, and design decision. The circuit will be evaluated based on completion. Even if the module is still in progress, it would still be a good idea to come to the presentation.

### Rules
- Design a motor controller using the DRV8801
- Must be mountable onto another board
- Must be designed using EasyEDA
- Must be able to interface with any modern microcontroller (Arduino, Raspberry Pi, STM32, MSP)
- Must follow the SJSU Robotics EE standards
- **You must work alone on this project. Working in teams is strictly forbidden**

**Notes:**
- Be sure to understand the operation of your circuit, as many sizing calculators and tutorials are available online. You will be asked questions during your presentation, so be prepared.
- There will be keywords that you do not know, feel free to research and make sure you understand them before the presentation.
- Any other questions or concerns may be redirected to the electrical lead, Quan Le through Slack.

## Project Outcomes
- Understands and follows the SJSU Robotics EE standards
- Demonstrate understanding of the DRV8801 datasheet
- Understanding the function, purpose, and selection of passive components

## Additional Resources
- DRV8801 datasheet: 
- Youtube link:
_ SJSU Robotics EE standards:

**Comment by QuanLe8191** [comment]
[
[trial project 2020.docx](https://github.com/SJSURoboticsTeam/urc-central-2021/files/5079364/trial.project.2020.docx)
](url)

**Comment by kammce** [comment]
Closing as this is no longer needed.
