### ISSUE TITLE
Investigate communication scheme between Arm and Claw

### ISSUE THREAD

**Issue by kammce** [SJSURoboticsTeam/urc-central-2021#12]
Communication protocol is UART between the Arm MCU and the Claw MCU. 
This can be modified or changed if desired. Another option is CANBUS.

**Comment by naterpotatoers** [comment]
Claw will be controlled over I2C using PCA9685 module and Arm MCU. There will not be seperate Claw MCU. Should not need UART or CANBUS protocols. Refer to #163 for more info
