### ISSUE TITLE
Setup Dev2

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#123]
Had trouble setting up on windows.

**Comment by ulysses10** [comment]
I ran into the same issue during setup on Mac (I installed the legacy VCP driver and tried the latest as well). I think it might be my connection speed since I get the same issue on Windows with a wired connection. I'm going to install Linux on a spare laptop and see how it goes. 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/72318589/95623834-caaa6180-0a2a-11eb-8d4d-915b77f37bbb.png">

**Comment by kammce** [comment]
Can you send the full log dump? just copy and paste it into this area here.

**Comment by ulysses10** [comment]
Last login: Fri Oct  9 12:21:36 on ttys000
mactr0llii@Ulyssess-MacBook-Pro ~ % cd /Users/mactr0llii/Downloads/SJSU-Dev2-master
mactr0llii@Ulyssess-MacBook-Pro SJSU-Dev2-master % ./setup
./setup: line 30: /Users/mactr0llii/Downloads/SJSU-Dev2-master/tools/common.sh: No such file or directory
 ──────────────────────────────────────────────────┐
              Detecting your platform               
└────────────────────────────────────────────────── 
 ──────────────────────────────────────────────────┐
  List of software installed globally:              
   1) Python3                                       
   2) pip (Python3 package manager)                 
   3) Curl                                          
   4) Git                                           
   5) Gcovr                                         
   6) XCode CLI tools (OSX Only)                    
└────────────────────────────────────────────────── 
 ──────────────────────────────────────────────────┐
            Acquiring sudo privileges               
└────────────────────────────────────────────────── 
Password:

 ──────────────────────────────────────────────────┐

    Starting SJSU-Dev2 Environment Setup Script     

└────────────────────────────────────────────────── 
Operating System: Mac OSX Darvin
 ──────────────────────────────────────────────────┐

           Installing Mac OSX Prerequisites         

└────────────────────────────────────────────────── 
 ───────────────────────────────────────────────────┐
               Installing Homebrew                   
└─────────────────────────────────────────────────── 
./setup: line 44: [: -ne: unary operator expected
✔ - success
 ───────────────────────────────────────────────────┐
          Prompt Git installer by invoking it        
└─────────────────────────────────────────────────── 
git version 2.21.0 (Apple Git-122)
✔ - success
 ───────────────────────────────────────────────────┐
               Brew Install Python@3                 
└─────────────────────────────────────────────────── 
./setup: line 133: brew: command not found
 ───────────────────────────────────────────────────┐
                Brew Installing gcc                  
└─────────────────────────────────────────────────── 
./setup: line 137: brew: command not found
./setup: line 138: brew: command not found
./setup: line 140: 0 + : syntax error: operand expected (error token is " ")
 ─────────────────────────────────────────────────────────┐
                 Prequisite Install Failed.                
  Make sure:                                               
     - You are connected to the internet                   

└───────────────────────────────────────────────────────── 
mactr0llii@Ulyssess-MacBook-Pro SJSU-Dev2-master %

**Comment by kammce** [comment]
What version of MacOSX are you using?

**Comment by ulysses10** [comment]
Version 10.15.7 (19H2)
2018 Macbook

**Comment by kammce** [comment]
What is the name of the OS? Catalina?

**Comment by ulysses10** [comment]
Yes, Catalina

**Comment by kammce** [comment]
That's weird. Should be working flawlessly, although the build for mac seems to be breaking all of a sudden but with a different setup issue thogh

**Comment by ulysses10** [comment]
Setup on Linux :+1:
