### ISSUE TITLE
Integrate battery state of charge for drive

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#157]
SJDEV2 has battery state of charge driver - [max17043](https://github.com/SJSU-Dev2/SJSU-Dev2/blob/master/library/devices/sensors/battery/max17043.hpp). This needs to be implemented to figure out battery status on rover

**Comment by kammce** [comment]
Do you mean integrated and not implemented? Because already built/implemented the SOC driver. So you just need to add it to the code base. Probably need to add it to the POR for generic steps that each implementation must run on boot up.
