### ISSUE TITLE
Prototype using PCA9685 (I2C PWM Generator) 

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#164]
Andrew and Ulysses will purchase a PCA9685 and use it a bit to get more familiar. That way implementing it within Arm will be much easier process 

They will prototype a simple Arduino system that moves a few small servos back and forward.
[PCA9685 Datasheet](https://static6.arrow.com/aropdfconversion/754302c96a9bb265f0eeeba16cdf3cde87d4b116/37269523016576896pca9685.pdf)

**Comment by naterpotatoers** [comment]
Andrew and Ulysses both received their PCA9685.

**Comment by AndrewDEmerson** [comment]
I got the PCA9685 partially working with SJDEV; code is pretty rough, but it's working.
https://www.youtube.com/watch?v=6pFy-ji6tEY

**Comment by naterpotatoers** [comment]
Ulysses and Andrew both got a working prototype. Andrew already started on dev2 driver for the PCA9685.
