### ISSUE TITLE
Document mc-server endpoints

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#175]
Ideally we should use swagger REST API documentation tool that way anyone who plans on using the mc-server will be greeted w/ api info at root page

**Comment by naterpotatoers** [comment]
Currently exists the following:
/ GET *Swagger page should be here ideally

/drive GET POST
/drive/status GET

/arm GET POST
/arm/status GET

**Comment by naterpotatoers** [comment]
This needs to be done for /arm now that that endpoint is built out

**Comment by acarrou** [comment]
Server Arm endpoint is finished until further notice.

**Comment by naterpotatoers** [comment]
this is referring to the swagger page found here https://github.com/SJSURoboticsTeam/urc-mc_server-2021/blob/master/swagger.json
I'm not sure if it still works anymore to be honest...
