### ISSUE TITLE
Investigate built-in PID setting for RMD-X

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#181]
We are already perusing implementing a [lerp ](https://github.com/SJSURoboticsTeam/urc-control_systems-2021/pull/37)handler for handing rover movement but there might be a PID setting within the RMD-X motor that we can use. This would remove some of the logic from our side and simplify the code base a bit. Datasheet(?) for RMD-X - https://drive.google.com/drive/folders/1EdX8TTgCa7RW9VXXL3oo1Pih2pvTXQsx

**Comment by joshua-git0** [comment]
This sounds interesting and I think I poked at this awhile ago.. if each motor comes with its own PID setting they may have to have custom PID gains for each motor

**Comment by naterpotatoers** [comment]
Yeah if you want to look into @josh-github1 that would be great! I'll assign it to you for now, this would be super helpful

**Comment by joshua-git0** [comment]
@naterpotatoers @kammce I tried adding in some functions for reading and setting PID values in the 'joshua_sandbox2' branch.. it's definitely a work in progress - https://github.com/SJSURoboticsTeam/urc-control_systems-2021/blob/joshua_sandbox2/Common/rmd_x_SJSU_Dev2.hpp

**Comment by ryerlic** [comment]
Hey Josh,

**Comment by joshua-git0** [comment]
Hey @ryerlic any feedback is appreciated.. I think this could be put in the actual SJSU-dev2 library and I remember having a convo like this in the last meeting for sjsu-dev2 https://github.com/SJSU-Dev2/SJSU-Dev2/blob/master/library/devices/actuators/servo/rmd_x.hpp
