### ISSUE TITLE
Recreate Trial Project in Dev2

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#182]
Good way to quickly learn the Dev2 code base is by using it. Last year @AndrewDEmerson made a MPU6050 driver for Dev2 that we will need to use for our rover this year. The trial project mimics behavior found in Arm since we use MPU6050s for figuring out the position of the arm when in use.

**Comment by acarrou** [comment]
`// DO NOT MODIFY THIS PROJECT OR FILE!
// Copy this folder and modify that copied project folder.

// Prefer to include files using the following method:
// https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

// The start of your program. Unlike programs that run on your computer, this
// main does not take argv and argc parameters, although such a thing may be
// added in the future.

#include <cstdint>
#include "peripherals/lpc40xx/i2c.hpp"
#include "devices/sensors/movement/accelerometer/mpu6050.hpp"
#include "utility/log.hpp"

#include <algorithm>
#include "peripherals/lpc40xx/can.hpp"
#include "devices/actuators/servo/rmd_x.hpp"
#include "utility/log.hpp"

int main()
{

//initialize the (mpu6050)
  sjsu::lpc40xx::I2c & i2c = sjsu::lpc40xx::GetI2c<2>();
  sjsu::Mpu6050 sensor(i2c);

  sjsu::LogInfo("Initializing accelerometer...");
  sensor.Initialize();

//initialize the gimbal for the motor (rmd-7x motor)
  sjsu::LogInfo("Starting RMD-X demo in 5s...");
  sjsu::lpc40xx::Can & can = sjsu::lpc40xx::GetCan<2>();
  sjsu::StaticMemoryResource<1024> memory_resource;
  sjsu::CanNetwork can_network(can, &memory_resource);
  sjsu::RmdX rmd_x7(can_network, 0x141);

  sjsu::Delay(5s);

  sjsu::LogInfo("RMD-X initializing...");
  rmd_x7.Initialize();


while (true){
//read from the mpu6050
auto data =  sensor.Read();
float x_data = static_cast<float>(data.x);
units::angle::degree_t angle(x_data);

//move the motor accoding to the mpu6050 data
rmd_x7.SetAngle(-angle);
sjsu::Delay(100ms);
}


  return 0;
}
`
