### ISSUE TITLE
Document Work for Drive Subsystem

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#188]
Similar to what #183 is doing.

**Comment by acarrou** [comment]
Driving documentation. Feel free to add anything important.
[Link to Doc](https://docs.google.com/document/d/1JclpylyAiXkV_mzl2nlOk8Rt2RWeT1LPMd51ubcDKBw/edit?usp=sharing)

**Comment by acarrou** [comment]
I recently updated some documents about how the steering should be implemented and what files we will primarily be working around.
