### ISSUE TITLE
Implement Speed Logic for Drive Mode 

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#190]
We need to find a workable solution for calculating each wheel speed when in drive mode. E.g.
When turning to the right slightly the right wheel's hub motor will need to cover less distance than the left wheel therefore right wheel speed < left wheel speed.
For now we are just setting them to the same speed which is definitely not ideal but until we figure out a better solution this is all we have for now.

**Comment by joshua-git0** [comment]
@naterpotatoers Can you elaborate on this? I'm interested in what you mean by speed logic

**Comment by naterpotatoers** [comment]
@josh-github1 updated

**Comment by joshua-git0** [comment]
Thank you Nate!

**Comment by josh-github1** [comment]
@naterpotatoers Does drive mode mean that no wheels are turning? Also, has anything like this already been implemented that we can reference?

I'll try to review https://github.com/SJSURoboticsTeam/urc-control_systems-2019/blob/Drive/Projects/Drive/main/Motor_Control_rev1.cpp

**Comment by joshua-git0** [comment]
@tbejaoui1 & @ryerlic I think you might find this interesting too!

I'm trying to reverse engineer this paper https://arxiv.org/pdf/1612.01476.pdf and the wheel speed pseudocode logic can be found in the drive document started by @acarrou. Section V of the paper is what I'm looking at and I didn't really reference the other parts of the paper

https://docs.google.com/document/d/1JclpylyAiXkV_mzl2nlOk8Rt2RWeT1LPMd51ubcDKBw/edit#

**Comment by joshua-git0** [comment]
Also one difference is that this paper does PID control and we're doing the Lerp method.. I think it's good either way
