### ISSUE TITLE
Add lerp to arm movements

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#202]
Gradual acceleration of the motors will greatly reduce the wear and tear and potential problems for the rover.

**Comment by Andrew-Ingerman** [comment]
How do I get the current speed of the motors?

**Comment by Andrew-Ingerman** [comment]
How do I get the current speed of the joint motors?

**Comment by naterpotatoers** [comment]
It looks like within the joint.hpp class there is a member variable call speed_
This should contain the current speed of the joint.
