### ISSUE TITLE
Implement test cases to all classes in testing document

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#215]
In order to better guarantee our logic works as anticipated we must test our code. The testing document can be found [here](https://docs.google.com/document/d/1GoI3ypr8xW_N2GrNbO3eNoYoz85498nix4rTv1WexoA/edit?usp=sharing).

**Comment by ryerlic** [comment]
Working on joint unit testing 1 - 6
