### ISSUE TITLE
Manually mock mpu6050

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#222]
Until we figure out why its not working lets just create a mocked mpu6050 manually so that way we can continue using the mpu as arguments for the various things used in arm

**Comment by acarrou** [comment]
I got the MPU to work using the 0x34 address instead of 0x68. After talking a little with Khalil, he suggested the problem could be that the boards I was using were know-offs due to the chip shortage. The code works when changing the expected device address in the MPU class to 0x34.

**Comment by kammce** [comment]
Oh, also, you can just mock the `sjsu::Accelerometer` class and just use that. You don't need the MPU class mocked directly. Just its interface. All accelerometers basically act the same so you don't need to mock MPU specifically.

**Comment by acarrou** [comment]
> Oh, also, you can just mock the `sjsu::Accelerometer` class and just use that. You don't need the MPU class mocked directly. Just its interface. All accelerometers basically act the same so you don't need to mock MPU specifically.

Ahh okay, I'll mock that up with @ryerlic thank you for mentioning that.
