### ISSUE TITLE
Implement Hand.hpp Logic

### ISSUE THREAD

**Issue by Mchan2003** [SJSURoboticsTeam/urc-central-2021#224]
Implement each functions for each finger. Also, add this class to the unit testing document with their appropriate unit tests.

- [x] MoveThumb
- [x] MovePointer
- [x] MoveMiddle
- [x] MoveRing
- [x] MovePinky
- [x]  Unit testing document for finger
- [x]  Unit tests

**Comment by naterpotatoers** [comment]
Looked into using PCA9685 driver. Discovered that using the driver will be a bit tricky with the fingers. Reached out to @AndrewDEmerson for further guidance. hopefully he has some advice.
