### ISSUE TITLE
Implement pca9685 & linear acuator logic in hand/finger class

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#229]
After meeting with Andrew we got better idea of how to our robots finger logic.  Datasheet values for finger pulse width ranges
```2.0 ms pulse commands the controller to fully retract the actuator, and a 1.0 ms pulse signals it to fully extend```
Now we need to create the logic for storing the PCA96855 pins - e.g.  

- thumb = 0
- index = 1
- middle = 2
- ring = 3
- pinky = 4

Then we'll need to map max/min angles to max/min pulse width for fingers as described by datasheet.

**Comment by Coreyboy1820** [comment]
So there's no specific angle to set the fingers, its just stationary = 0ms, 1ms = retract, and 2ms = extend? Or will our driver handle and convert it to angles?

**Comment by Andrew-Ingerman** [comment]
There is supposed to be a function that converts it to angles

**Comment by Coreyboy1820** [comment]
Alright thanks. Are you working on this right now?

**Comment by Andrew-Ingerman** [comment]
> Alright thanks. Are you working on this right now?

Yeah

**Comment by Andrew-Ingerman** [comment]
- Move Finger logic back into hand so we don't replicate the PCA 5 times.

**Comment by Coreyboy1820** [comment]
> * Move Finger logic back into hand so we don't replicate the PCA 5 times.

Can you tell me why we need to do this rather then putting the PCA in the hand class itself?

**Comment by Coreyboy1820** [comment]
Doing this would make us need to create 5x the code of the finger class inside of hand.

**Comment by naterpotatoers** [comment]
Yeah but it removes the complication of have 5 instances of the pca device. We might go back to finger class once we know that it works with this much simpler solution
