### ISSUE TITLE
Remove tight coupling to Mpu6050 by using to sjsu::Accelerometer class

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#234]

**Comment by kammce** [comment]
What, what does this mean? Are you trying to change the MPU class itself or doing something else?

**Comment by naterpotatoers** [comment]
this is to resolve the tight coupling issue with the mpus. Switching the member variables to be Accelerometer object as opposed to mpu6050

**Comment by kammce** [comment]
Ah ok. The wording of the title is very confusing. You may want to change this to be more direct such as "Change references to Mpu6050 to sjsu::Accelerometer".

**Comment by kammce** [comment]
Why was this closed? Was this linked to a PR? If so list it here or make sure that you have `Resolves #234` in your commit message so it automatically closes issues when the PR is merged.

**Comment by Coreyboy1820** [comment]
Thanks @kammce I didn't know that was a thing. I'll do this next time. I was just trying to take care of issues that have been resolved for a few days.
