### ISSUE TITLE
Create arm mode for transportation

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#238]
Reference the compact arm mode slide in the [POR document](https://docs.google.com/presentation/d/17clPo-6g9CDImaTh3-akEh0AcbR9gbY4OoO5jGr4u0E/edit#slide=id.g111c61178f5_1_0)

**Comment by Andrew-Ingerman** [comment]
Create a fist mode for the hand as well

**Comment by naterpotatoers** [comment]
has been merged in, needs further testing
