### ISSUE TITLE
Design Motor Interface

### ISSUE THREAD

**Issue by kammce** [SJSURoboticsTeam/urc-central-2021#26]

**Comment by kammce** [comment]
Playlist on how motors work:
 - https://www.youtube.com/watch?v=OpL0joqJmqY&list=PLnSkZEZJq3qrTQytAYrxw5dH6EaPXHu9q

Look into how to control a motor using arduino.

**Comment by AndrewDEmerson** [comment]
@kammce I made the changes your requested. Can you review it? SJSURoboticsTeam/urc-control_systems-2021#9

**Comment by AndrewDEmerson** [comment]
@kammce Changed the return types, can you review?
