### ISSUE TITLE
Migrate MPU6050 to new Accelerometer interface

### ISSUE THREAD

**Issue by kammce** [SJSURoboticsTeam/urc-central-2021#29]
Should inherit `Accelerometer` class.

**Comment by AndrewDEmerson** [comment]
@kammce  Can you review? SJSURoboticsTeam/urc-control_systems-2021#8

**Comment by AndrewDEmerson** [comment]
@kammce

**Comment by kammce** [comment]
Resolved by SJSURoboticsTeam/urc-control_systems-2021#8
