### ISSUE TITLE
Demonstrate positional control of arm using MPU6050 and the various arm motors

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#31]
Write the various testing files to test MPU6050 with:
- [ ] Wrist motor
- [ ] Elbow motor
- [ ] Shoulder motor

**Comment by kammce** [comment]
This is no longer Point of Record (POR) as we will not need to perform orientation control of the motors using the MPU6050s. We will be using them to HOME the ARM into position. 

For more details: On bootup, each MPU6050 will be read for steadiness (making sure the rover is not moving or being moved around) and when it notices it is stable, it will average the data from the sensor, and determine what the approximate angle of each joint is in. With the starting positions known, the RMD-X7 motors can be commanded to rotate the motors into whatever position is necessary.
