### ISSUE TITLE
Figure out Google's Donation Situation

### ISSUE THREAD

**Issue by davidbdias96** [SJSURoboticsTeam/urc-central-2021#67]

**Comment by kammce** [comment]
The website for making donations changed internally, but I have access now.

I figured out the matching situation with Google. The amount that a Google matches employees can be found here: https://doublethedonation.com/matching-gifts/google-inc. 

I should be able to donate when y'all have access and control over the student club account. There is no reason to donate if you guys cannot get access to the funds in the first place.

**Comment by kammce** [comment]
For reference at the time of writing this, this is the amount matchable:

![image](https://user-images.githubusercontent.com/4549768/88242715-e596e200-cc42-11ea-9ffd-9ecbfc7c8620.png)
