### ISSUE TITLE
Email AS about accessing funds

### ISSUE THREAD

**Issue by davidbdias96** [SJSURoboticsTeam/urc-central-2021#74]
Find out if we can remotely access our account in order to deposit and withdraw funds

**Comment by davidbdias96** [comment]
Documents signed and sent to AS, Waiting on response.

**Comment by kammce** [comment]
Can we document the process for remote access of funds? So that the process is transparent to the team. Make sure to not include sensitive information like the club account number etc.

**Comment by davidbdias96** [comment]
Cash deposits: Make an in-person appointment with Vivian (Wednesday or Thursday)
Checks and money orders can be mailed in (Don't endorse checks)
There is only someone in the office once a week at the moment so any mailed in checks will have about a 2-week wait before funds are available.

Reimbursements/Requisitions: Need name and address of the person the money is being sent to.

Vivian.Nguyen@sjsu.edu  Office Manager (408)786-8488 cell phone

Helen.Nguyen@sjsu.edu  The Accountant

**Comment by kammce** [comment]
Yikes. But this clears the way for funding. I'll see what I can do.
