### ISSUE TITLE
look into getting the club on the Sammy app

### ISSUE THREAD

**Issue by davidbdias96** [SJSURoboticsTeam/urc-central-2021#75]

**Comment by josh-github1** [comment]
what the heck the club isn't on the sammy app.. this is like one the most active clubs out of every club

**Comment by davidbdias96** [comment]
Yeah, we've been needing to do that for several years now. I'm looking into it especially since it may be a good way to find new members while everything is still online.

**Comment by ntwong0** [comment]
@davidbdias96  confirmed re-registered with AS but still not listed on the app, will continue communications with them
