### ISSUE TITLE
Add state estimation methods

### ISSUE THREAD

**Issue by josh-github1** [SJSURoboticsTeam/urc-central-2021#82]
I've been looking a little bit into this and it would include the eigen C++ library for stuff like kalman filters or controller-observers for motor control.. this would work for the arm motors (I think)

I'm not sure if these tools are commercial off the shelf already

**Comment by josh-github1** [comment]
For anyone who's interested, these links are a good starting point
https://forum.kde.org/viewtopic.php?f=74&t=129652
https://github.com/bminerd/Kalman/blob/master/KalmanFilter.h

**Comment by kammce** [comment]
No longer needed with the RMD-X7 motors as they have a PID and state estimation system built in.
