### ISSUE TITLE
Materials for new belt drive system

### ISSUE THREAD

**Issue by wilton-lee** [SJSURoboticsTeam/urc-central-2021#93]
**Chosen Parts:**

Motor: RMD-X7 
- https://www.aliexpress.com/item/10000397235320.html?spm=2114.12010612.8148356.3.66fd22a06keXEs

1045 Carbon Steel Keyed Rotary Shaft Fully Keyed - $62 :
- 12mm Diameter, 1000mm Long (needs to be cut to size ~200mm each) 
- https://www.mcmaster.com/1439K431/

Machine Key Stock - $5 for 305mm
- 18-8 Stainless Steel, 305mm Long, 4mm x 4mm, oversized
- https://www.mcmaster.com/98810A100/

ABEC-5 stainless steel flanged bearing SF6901 SF6901Z SF6901ZZ - $42 for 20:
- 12x24x6mm : 
- https://www.aliexpress.com/item/4000558016398.html?spm=2114.12010615.8148356.30.4d0e1a23WjQWsG

Timing Belt Pulleys (HTD5M)
- 15 teeth, 16mm belt width, 12mm bore, key 4x1.8mm
- https://www.aliexpress.com/item/4000484375488.html?spm=2114.12010612.8148356.27.51d16b08IHC2vj
- 40 teeth, 16mm belt width, 12mm bore, key 4x1.8mm
- https://www.aliexpress.com/item/4000764179023.html?spm=2114.12010612.8148356.8.1d386b08RZdyg3

Idler Pulley (using M4x30 screw)
- 24 teeth, 16mm belt width, 5mm bore
- https://www.aliexpress.com/item/4000030817538.html?spm=2114.12010615.8148356.1.33e8a9130eiQQN

Timing Belt - $9
- minimum belt length needed = 406.85mm
- 410mm, 16mm belt width, 5mm pitch, 
- https://www.mcmaster.com/1679K488/

M4 Washer 8mm OD
- https://www.mcmaster.com/98689a113

**Needs Further Evaluation/Alternative Choices:**

Shaft collar: https://www.mcmaster.com/6063K16/

Pulleys (16mm belt width, 12mm diameter with 4x1.8mm keyway):
- 48 teeth 
- https://www.aliexpress.com/item/32887215800.html?spm=2114.12010612.8148356.16.37f55739u43ZC1

_Belt:_
- https://www.aliexpress.com/item/32791799628.html
![image](https://user-images.githubusercontent.com/25037655/92197120-be2c5b00-ee25-11ea-8d21-7e4cf5889b19.png)

**Comment by wilton-lee** [comment]
Motor: RMD-X7 
- https://www.aliexpress.com/item/10000397235320.html?spm=2114.12010612.8148356.3.66fd22a06keXEs

Pulleys: 
- https://www.aliexpress.com/item/4000768114918.html?spm=2114.12010612.8148356.11.3b70e29dVvoN7N
- https://www.aliexpress.com/item/4000499698920.html?spm=2114.12010612.8148356.13.3b70e29dVvoN7N

Belt:
- https://www.aliexpress.com/item/32791799628.html

**Comment by kammce** [comment]
@wilton-lee did you verify that the keyway, pulley width and everything else match? Because if you copied this from my presentation, I did not do all of the due diligence to verify that everything works. I just needed the materials to calculate approximate cost and weight.

**Comment by wilton-lee** [comment]
I was using this list more to organize the links of potential parts to
choose from so I have quicker access. I will add a note to my main post to
clarify this.

**Comment by wilton-lee** [comment]
Looking for 12mm keyed shaft ~200mm long OR 14mm flanged ball bearing OR compatible shaft+flanged bearing that can support loads

**Comment by davidbdias96** [comment]
ready for purchase
