### ISSUE TITLE
Send a list of past leads - by year - to Vishnu

### ISSUE THREAD

**Issue by Vishnu-Adda** [SJSURoboticsTeam/urc-central-2021#95]

**Comment by kammce** [comment]
## 2015

- Mechanical: Rocely Mati
- Electrical: Colin Chen
- Controls: Matthew Boyd
- Mission Control: Khalil Estell
- President/Project Lead: Khalil Estell
- Treasurer: Rocely Mati

## 2016

- Mechanical: Alfred (Andy) Bru
- Electrical: Colin Chen
- Controls: Matthew Boyd
- Mission Control: Henry Tran
- President/Project Lead: Khalil Estell
- Treasurer: ???

## 2017

- Mechanical: David Cruz
- Electrical: Sean Setterfield
- Controls: Matthew Boyd
- Mission Control: Alissa Sandore
- President/Project Lead: Khalil Estell
- Treasurer: Christian Timbol

## 2018

- Mechanical: Zeng Zhaoyi
- Electrical: Jeff Normand
- Controls: Matthew Z Chew
- Mission Control: Ari Koumis
- President/Project Lead: Kevin Gallegos
- Treasurer: ???

## 2019

- Mechanical: Jonathon Nguyen 
- Electrical: Nathaniel Ciceron
- Controls: Matthew Z Chew
- Mission Control: Evan Ugarte
- President/Project Lead: Ari Koumis
- Treasurer: ??? 

## 2020

Well y'all know the rest. :P

This is all that I know.
